# Generated by Django 5.1.7 on 2025-03-11 02:45

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_date_alter_post_description_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
